version: "3"

services:
  db:
    platform: linux/x86_64
    container_name: "hi-projects-db"
    image: mysql:5.7
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/hi-projects
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: "always"

  app:
    platform: linux/x86_64
    container_name: "hi-projects-app"
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    env_file:
      - .env
    volumes:
      - .:/hi-projects
    ports:
      - "3030:3000"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0

  adminer_container:
    container_name: "hi-projects-adminer"
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080

  redis:
    container_name: "hi-projects-redis"
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  db_data:
  redis:
